version: "3.7"

services:
  db:
    image: angemenel98/postgresql:0.0.1
    build:
      context: ./service-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: ./service-postgres/init.sh
        target: /docker-entrypoint-initdb.d/init.sh
      - type: volume
        source: sql-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: false
volumes:
  sql-data:

secrets:
  db_secrets:
    file: ./secrets/db_credentials.json
