import 'reflect-metadata';
import { DataSource } from 'typeorm';
import {
    User,
    PersonalData,
    Tour,
    Tournament,
    Category,
    Match,
    Team,
    Set,
    Court,
    Club,
    CalendarClub,
    TourCoin,
    Notification,
    Reward,
} from './entity/index';

export const AppDataSource = new DataSource({
    type: 'postgres',
    host: process.env.DB_HOST,
    port: 54321,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    synchronize: true,
    logging: false,
    entities: [
        User,
        PersonalData,
        Tour,
        Tournament,
        Category,
        Match,
        Team,
        Set,
        Court,
        Club,
        CalendarClub,
        TourCoin,
        Notification,
        Reward,
    ],
    migrations: [],
    subscribers: [],
});
